server:
  port: 7071

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7071/eureka/
       
    fetch-registry: false        # Eureka server doesn't fetch the registry
    register-with-eureka: false  # Eureka server doesn't register itself
  server:
    enable-self-preservation: false  # Optional, depending on your use case
    
logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG