pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Sawanmalvi/Test01.git'
            }
        }

        stage('Build Project') {
            steps {
                bat 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t java-app .'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 8081:8080 java-app'
            }
        }

    }
}